### ISSUE TITLE
Doesn't support number values

### ISSUE THREAD

**Issue by talkbutton** [transistorsoft/expo-gradle-ext-vars#1]
Hi, love this plugin, one issue though - 

when you use a numeric value e.g. 

`    [
            "expo-gradle-ext-vars", {
                "ProximityScreen_compileSdkVersion" : 30
            }
        ]`

It converts that into a string in the output e.g.

`   ext {
// @generated begin expo-gradle-ext-vars - expo prebuild (DO NOT MODIFY) sync-16641b611f087249b24ef1fbaf12d205c3b8af2b
	ProximityScreen_compileSdkVersion = "30"
// @generated end expo-gradle-ext-vars`

Which breaks gradle tasks dependent upon a number.

I can see that you're checking for presence of booleans in the script but not numbers, happy to submit a pull request if that helps

**Comment by christocracy** [comment]
Please go ahead with a PR.

**Comment by christocracy** [comment]
Released to `0.1.2` now

**Comment by talkbutton** [comment]
Thank you!
